# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: users

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  cfLogs: true
  region: eu-west-1
  memorySize: 256 # optional, default is 1024
  timeout: 10 # optional, default is 6

package:
  individually: true
  exclude:
     - getUser/**
     - deleteUser/**
     - createUser/**
     - updateUser/**
     - listUsers/**

# you can add packaging information here

functions:
    update:
        handler: updateUser/index.main
        cfLogs: true
        package:
            include:
              - lib/**
              - updateUser/**
        environment:
            MONGO_URL: mongodb://admin:root_admin@ds149489.mlab.com:49489/serverless
        events:
            - http:
                path: user/{id}
                method: put
                cors:
                  origins:
                    - '*'
    get:
        handler: getUser/index.main
        cfLogs: true
        package:
            include:
              - lib/**
              - getUser/**
        environment:
            MONGO_URL: mongodb://admin:root_admin@ds149489.mlab.com:49489/serverless
        events:
            - http:
                path: user/{id}
                method: get
                cors:
                  origins:
                    - '*'

    list:
        handler: listUsers/index.main
        cfLogs: true
        package:
            include:
              - lib/**
              - listUsers/**
        environment:
            MONGO_URL: mongodb://admin:root_admin@ds149489.mlab.com:49489/serverless
        events:
            - http:
                path: users
                method: get
                cors:
                  origins:
                    - '*'

    create:
        handler: createUser/index.main
        cfLogs: true
        package:
            include:
              - lib/**
              - createUser/**
        environment:
            MONGO_URL: mongodb://admin:root_admin@ds149489.mlab.com:49489/serverless
        events:
            - http:
                path: user
                method: post
                cors:
                  origins:
                    - '*'

    delete:
        handler: deleteUser/index.main
        cfLogs: true
        package:
            include:
              - lib/**
              - deleteUser/**
        environment:
            MONGO_URL: mongodb://admin:root_admin@ds149489.mlab.com:49489/serverless
        events:
            - http:
                path: user/{id}
                method: delete
                cors:
                  origins:
                    - '*'
